name: network
description: Network monitoring and interception for DebugHub
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../base
  http: 1.3.0
  dio: 5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
