name: memory_monitor
description: Memory usage monitoring package for DebugHub
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.9.0'

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../base
  vm_service: ^14.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

