name: debug_hub_ui
description: UI components for DebugHub - Flutter debugging tool
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../base
  network:
    path: ../network
  log:
    path: ../log
  non_fatal:
    path: ../non_fatal
  events:
    path: ../events
  notification:
    path: ../notification
  
  # Additional dependencies
  device_info_plus: ^11.2.1
  package_info_plus: ^8.0.3
  share_plus: 7.2.2
  path_provider: ^2.1.5
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

